#!/bin/bash

STATE=$(acpi | cut -d " " -f3)

if [ "$STATE" = "Not"  ] ; then
   echo ""
elif [ "$STATE" = "Discharging," ] ; then
  LEVEL=$(acpi | cut -d " " -f4 | sed 's/.$//' | sed 's/.$//')
  if [ $LEVEL -gt 85  ] ;then 
    echo " $LEVEL"
  elif [ $LEVEL -gt 60 ] ; then
    echo " $LEVEL"
  elif [ $LEVEL -gt 35 ] ; then
    echo " $LEVEL"
  elif [ $LEVEL -gt 10 ] ; then
    echo " $LEVEL"
  else
    echo " $LEVEL"
  fi
elif [ "$STATE" = "Charging,"  ] ; then
  echo "";  
else
  echo "Nie wiem"
fi
